CREATE TABLE FILES
(
    FILE_ID                         BIGINT NOT NULL,
    FILE_NAME                       VARCHAR(128) NOT NULL,
    FILE_PATH                       VARCHAR(256),
    FILE_TYPE                       VARCHAR(64) NOT NULL,
    FILE_SIZE                       BIGINT NOT NULL,
    STORAGE_TYPE                    VARCHAR(32) NOT NULL,
    EXTERNAL_FILE_ID                VARCHAR(128),
    EXTERNAL_URL                    VARCHAR(256),
    EXTERNAL_BUCKET                 VARCHAR(128),
    CREATED_AT                      TIMESTAMP NOT NULL,
    DELETED_AT                      TIMESTAMP NOT NULL
)
;
ALTER TABLE FILES
    ADD CONSTRAINT PK_FILES1 PRIMARY KEY(FILE_ID)
;
CREATE TABLE HOTSPOTS
(
    HOTSPOT_ID                      BIGINT NOT NULL,
    IMAGE_ID                        BIGINT NOT NULL,
    YAW                             FLOAT8 NOT NULL,
    PITCH                           FLOAT8 NOT NULL,
    TARGET_ID                       BIGINT NOT NULL,
    CREATED_AT                      TIMESTAMP NOT NULL,
    UPDATED_AT                      TIMESTAMP NOT NULL,
    DELETED_AT                      TIMESTAMP
)
;
ALTER TABLE HOTSPOTS
    ADD CONSTRAINT PK_HOTSPOTS1 PRIMARY KEY(HOTSPOT_ID)
;
CREATE TABLE AUTHORITY_MASTER
(
    AUTHORITY_ID                    BIGINT NOT NULL,
    AUTHORITY_NAME                  VARCHAR(32) NOT NULL,
    AUTHORITY_CODE_LIST             TEXT NOT NULL,
    CREATED_AT                      TIMESTAMP NOT NULL,
    UPDATED_AT                      TIMESTAMP NOT NULL,
    DELETED_AT                      TIMESTAMP
)
;
ALTER TABLE AUTHORITY_MASTER
    ADD CONSTRAINT PK_ROLE_MASTER1 PRIMARY KEY(AUTHORITY_ID)
;
COMMENT ON COLUMN AUTHORITY_MASTER.AUTHORITY_CODE_LIST IS '権限許可リスト（カンマ区切り）。例: facility_view,annotation_view,equipment_view'
;
CREATE TABLE FACILITIES_TREE
(
    FACILITY_ID                     BIGINT NOT NULL,
    PARENT_ID                       BIGINT,
    NODE_NAME                       VARCHAR(128) NOT NULL,
    SORT_ORDER                      INTEGER DEFAULT 0 NOT NULL,
    TREE_LEVEL                      INTEGER NOT NULL,
    IS_LEAF                         BOOLEAN NOT NULL,
    PUBLIC_FLAG                     CHAR(2) DEFAULT 01 NOT NULL,
    OUTER_FLAG                      BOOLEAN DEFAULT False NOT NULL,
    NODE_DESCRIPTION                VARCHAR(1000),
    AUTHORITY_SETTING_FLG           BOOLEAN DEFAULT False NOT NULL,
    CREATED_AT                      TIMESTAMP NOT NULL,
    UPDATED_AT                      TIMESTAMP NOT NULL,
    DELETED_AT                      TIMESTAMP
)
;
ALTER TABLE FACILITIES_TREE
    ADD CONSTRAINT IDX_FACILITIES_TREE_PARENT_SORT_ORDER_DELETED_AT PRIMARY KEY(FACILITY_ID, FACILITY_ID, PARENT_ID, SORT_ORDER, DELETED_AT)
;
COMMENT ON COLUMN FACILITIES_TREE.SORT_ORDER IS '同一親配下の手動並び替え用。初期値は 10, 20, 30 のような間隔付き連番を推奨'
;
COMMENT ON COLUMN FACILITIES_TREE.PUBLIC_FLAG IS '01又はNULL：非公開
02：この施設レイヤのみ公開
03：下位施設も含めて公開'
;
COMMENT ON COLUMN FACILITIES_TREE.OUTER_FLAG IS 'True：屋外
FalseまたはNULL：屋内'
;
COMMENT ON COLUMN FACILITIES_TREE.AUTHORITY_SETTING_FLG IS 'True：個別に権限を設定する
False又はNULL：親の権限を引き継ぐ'
;
CREATE TABLE FACILITY_IMAGES
(
    IMAGE_ID                        BIGINT NOT NULL,
    FACILITY_ID                     BIGINT NOT NULL,
    FILE_ID                         BIGINT NOT NULL,
    IMAGE_NAME                      VARCHAR(256) NOT NULL,
    SHOOTING_HEIGHT_M               DECIMAL NOT NULL,
    CEILING_HEIGHT_M                DECIMAL NOT NULL,
    GUID                            VARCHAR(64) NOT NULL,
    CREATED_AT                      TIMESTAMP NOT NULL,
    UPDATED_AT                      TIMESTAMP NOT NULL,
    DELETED_AT                      TIMESTAMP
)
;
ALTER TABLE FACILITY_IMAGES
    ADD CONSTRAINT PK_FACILITY_IMAGES1 PRIMARY KEY(IMAGE_ID)
;
CREATE TABLE NODE_AUTHORITY_ROLE
(
    NODE_AUTHORITY_ROLE_ID          BIGINT NOT NULL,
    FACILITY_ID                     BIGINT NOT NULL,
    AUTHORITY_ID                    BIGINT NOT NULL,
    ROLE_ID                         BIGINT NOT NULL
)
;
ALTER TABLE NODE_AUTHORITY_ROLE
    ADD CONSTRAINT PK_NODE_MAPS1 PRIMARY KEY(NODE_AUTHORITY_ROLE_ID)
;
CREATE TABLE EQUIPMENTS
(
    CONTENT_ID                      BIGINT NOT NULL,
    FACILITY_ID                     BIGINT NOT NULL,
    EQUIPMENT_MASTER_ID             BIGINT NOT NULL,
    YAW                             FLOAT8,
    PITCH                           FLOAT8,
    CREATED_AT                      TIMESTAMP NOT NULL,
    UPDATED_AT                      TIMESTAMP NOT NULL,
    DELETED_AT                      TIMESTAMP
)
;
ALTER TABLE EQUIPMENTS
    ADD CONSTRAINT PK_EQUIPMENTS1 PRIMARY KEY(CONTENT_ID)
;
CREATE TABLE EQUIPMENT_FILES
(
    EQUIPMENT_FILE_ID               BIGINT NOT NULL,
    EQUIPMENT_MASTER_ID             BIGINT NOT NULL,
    FILE_ID                         BIGINT NOT NULL
)
;
ALTER TABLE EQUIPMENT_FILES
    ADD CONSTRAINT PK_CONTENT_FILES1 PRIMARY KEY(EQUIPMENT_FILE_ID)
;
CREATE TABLE EQUIPMENT_MASTERS
(
    EQUIPMENT_MASTER_ID             BIGINT NOT NULL,
    EQUIPMENT_TYPE_ID               BIGINT NOT NULL,
    EQUIPMENT_NAME                  VARCHAR(256) NOT NULL,
    EQUIPMENT_INFO_JSON             TEXT NOT NULL,
    EQUIPMENT_INFO_HTML             TEXT,
    CREATED_AT                      TIMESTAMP NOT NULL,
    UPDATED_AT                      TIMESTAMP NOT NULL,
    DELETED_AT                      TIMESTAMP
)
;
ALTER TABLE EQUIPMENT_MASTERS
    ADD CONSTRAINT PK_EQUIPMENT_MASTERS1 PRIMARY KEY(EQUIPMENT_MASTER_ID)
;
CREATE TABLE EQUIPMENT_TYPES
(
    EQUIPMENT_TYPE_ID               BIGINT NOT NULL,
    EQUIPMENT_TYPE_NAME             VARCHAR(128) NOT NULL,
    CREATED_AT                      TIMESTAMP NOT NULL,
    UPDATED_AT                      TIMESTAMP NOT NULL,
    DELETED_AT                      TIMESTAMP
)
;
ALTER TABLE EQUIPMENT_TYPES
    ADD CONSTRAINT PK_EQUIPMENT_TYPES1 PRIMARY KEY(EQUIPMENT_TYPE_ID)
;
CREATE TABLE MAPS
(
    MAP_ID                          BIGINT NOT NULL,
    FACILITY_ID                     BIGINT NOT NULL,
    FILE_ID                         BIGINT NOT NULL,
    MAP_NAME                        VARCHAR(256) NOT NULL,
    IMAGE_WIDTH                     INTEGER NOT NULL,
    IMAGE_HEIGHT                    INTEGER NOT NULL,
    CREATED_AT                      TIMESTAMP NOT NULL,
    UPDATED_AT                      TIMESTAMP NOT NULL,
    DELETED_AT                      TIMESTAMP
)
;
ALTER TABLE MAPS
    ADD CONSTRAINT PK_FACILITY_IMAGES1 PRIMARY KEY(MAP_ID)
;
CREATE TABLE MAP_POINTS
(
    MAP_POINT_ID                    BIGINT NOT NULL,
    MAP_ID                          BIGINT NOT NULL,
    FACILITY_ID                     BIGINT NOT NULL,
    X                               FLOAT8 NOT NULL,
    Y                               FLOAT8 NOT NULL,
    TARGET_TYPE                     VARCHAR(128) NOT NULL,
    TARGET_ID                       BIGINT NOT NULL,
    CREATED_AT                      TIMESTAMP NOT NULL,
    UPDATED_AT                      TIMESTAMP NOT NULL,
    DELETED_AT                      TIMESTAMP
)
;
ALTER TABLE MAP_POINTS
    ADD CONSTRAINT PK_HOTSPOTS1 PRIMARY KEY(MAP_POINT_ID)
;
CREATE TABLE ANNOTATIONS
(
    ANNOTATION_ID                   BIGINT NOT NULL,
    FACILITY_ID                     BIGINT NOT NULL,
    YAW                             FLOAT,
    PITCH                           FLOAT,
    ANNOTATION_TYPE                 CHAR(2) DEFAULT 01,
    ANNOTATION_TITLE                VARCHAR(256) NOT NULL,
    ANNOTATION_CONTENT              TEXT,
    DISPLAY_EXPIRE_TYPE             VARCHAR(16),
    DISPLAY_EXPIRE_AT               TIMESTAMP,
    CREATED_AT                      TIMESTAMP NOT NULL,
    CREATED_BY                      VARCHAR(128) NOT NULL,
    UPDATED_AT                      TIMESTAMP NOT NULL,
    DELETED_AT                      TIMESTAMP
)
;
ALTER TABLE ANNOTATIONS
    ADD CONSTRAINT PK_ANNOTATIONS1 PRIMARY KEY(ANNOTATION_ID)
;
COMMENT ON COLUMN ANNOTATIONS.ANNOTATION_TYPE IS '01:一般 / 02:緊急'
;
COMMENT ON COLUMN ANNOTATIONS.DISPLAY_EXPIRE_TYPE IS 'unlimited/limited'
;
COMMENT ON COLUMN ANNOTATIONS.DISPLAY_EXPIRE_AT IS 'display_expire_type=limited の場合に設定'
;
CREATE TABLE ANNOTATION_COMMENTS
(
    ANNOTATION_COMMENT_ID           BIGINT NOT NULL,
    ANNOTATION_ID                   BIGINT NOT NULL,
    COMMENT_TEXT                    TEXT NOT NULL,
    CREATED_AT                      TIMESTAMP NOT NULL,
    CREATED_BY                      VARCHAR(128) NOT NULL,
    DELETED_AT                      TIMESTAMP
)
;
ALTER TABLE ANNOTATION_COMMENTS
    ADD CONSTRAINT PK_ANNOTATIONS1 PRIMARY KEY(ANNOTATION_COMMENT_ID)
;
CREATE TABLE ANNOTATION_FILES
(
    ANNOTATION_FILE_ID              BIGINT NOT NULL,
    ANNOTATION_ID                   BIGINT NOT NULL,
    FILE_ID                         BIGINT NOT NULL
)
;
ALTER TABLE ANNOTATION_FILES
    ADD CONSTRAINT PK_CONTENT_FILES1 PRIMARY KEY(ANNOTATION_FILE_ID)
;
